### ISSUE TITLE
Fresh installation on Windows 7SP1 x64 -  Missing Dependencies (?)

### ISSUE THREAD

**Issue by DPSB** [desratuk/touchdown#1]
Installation first raised some Python error (python exe not found even if already installed). This could be fixed by using "npm install --global --production windows-build-tools" which will then actually use python2 instead of python3
After python install a "npm run serve" throws the following error:
```

module.js:549
    throw err;
    ^

Error: Cannot find module 'autoit'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Echo\Documents\GitHub\touchdown\src\autoit\routes.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TouchDown@1.0.0 serve: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TouchDown@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This can be resolved with "npm install --save autoit"

Btw installation via gitbash was not possible cause i have installed it seperatly (Who the hell would ever overwrite internal windows tools like find?) and gitbash doesn't know the "npm" command. So i've installed via an administrative CMD Window.

Anyway, whit the above mentioned commands i was able to get it running. it opend some firewall access dialog and shows me that hes running on port 80.

See Logfiles attached for more information:
[2018-06-01T09_11_41_824Z-debug.log](https://github.com/desratuk/touchdown/files/2062199/2018-06-01T09_11_41_824Z-debug.log)
[2018-06-01T09_12_18_182Z-debug.log](https://github.com/desratuk/touchdown/files/2062200/2018-06-01T09_12_18_182Z-debug.log)
[2018-06-01T09_21_07_362Z-debug.log](https://github.com/desratuk/touchdown/files/2062201/2018-06-01T09_21_07_362Z-debug.log)
[2018-06-01T09_33_54_855Z-debug.log](https://github.com/desratuk/touchdown/files/2062202/2018-06-01T09_33_54_855Z-debug.log)

Edit:

I got the Elite Dangerous Web UI Running (either from local pc using "localhost" or from remote using ip. I can touch all Buttons, I see them changing colours but inside of the game nothing happens.
Is there an option/log to see what the server has recived?

**Comment by desratuk** [comment]
python issue isn't anything to do with the project - its an issue with node and windows - also no need to 'npm install --save autoit' - it's already a dependency - check package.json.
